### ISSUE TITLE
Error when Install TC-JSON-API

### ISSUE THREAD

**Issue by leolion84** [ShinDarth/TC-JSON-API#28]
Hi guys, I install TC_JSON_API on xampp and get this error on log. I'm newbie, someone help me please.

[2017-07-14 05:19:07] production.ERROR: ErrorException: Function mcrypt_get_iv_size() is deprecated in C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php:12241
Stack trace:
#0 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(12241): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Function mcrypt...', 'C:\xampp\htdocs...', 12241, Array)
#1 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(12232): Illuminate\Encryption\Encrypter->updateBlockSize()
#2 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(6796): Illuminate\Encryption\Encrypter->setCipher('rijndael-128')
#3 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(1066): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption{closure}(Object(Illuminate\Foundation\Application), Array)
#4 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(1019): Illuminate\Container\Container->build(Object(Closure), Array)
#5 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(1543): Illuminate\Container\Container->make('encrypter', Array)
#6 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(1111): Illuminate\Foundation\Application->make('encrypter')
#7 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(1095): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#8 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(1081): Illuminate\Container\Container->getDependencies(Array, Array)
#9 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(1019): Illuminate\Container\Container->build('Illuminate\Cook...', Array)
#10 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(1543): Illuminate\Container\Container->make('Illuminate\Cook...', Array)
#11 C:\xampp\htdocs\TC-JSON-API\vendor\compiled.php(2002): Illuminate\Foundation\Application->make('Illuminate\Cook...')
#12 C:\xampp\htdocs\TC-JSON-API\public\index.php(60): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpFoundation\Response))
#13 {main}

**Comment by Helias** [comment]
Hi, did you install php-mcrypt on xampp?

Here how you can check it:
https://stackoverflow.com/questions/37522384/how-to-install-mcrypt-extension-in-xampp

**Comment by avengerweb** [comment]
use last version from repo, and forget about mcrypt
